#  Universidade de Caxias do Sul
#  Aluno Gabriel Orlandin Gomes

In [1]:
import matplotlib as plt
import matplotlib.pyplot as plt

In [2]:
import numpy as np
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV

In [3]:
# Carga de dados de arquivo local
from google.colab import files
uploaded = files.upload()

Saving breast-cancer.csv to breast-cancer.csv


In [4]:
import pandas as pd
df = pd.read_csv("breast-cancer.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [7]:
df['diagnosis']=df['diagnosis'].replace({'M': 1,'B': 0}) # Maligno 1 e Benigno 0
df.drop('id',axis='columns', inplace=True)

In [8]:
df.describe()

diagnosis  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  569.000000   569.000000    569.000000      569.000000   569.000000   
mean     0.372583    14.127292     19.289649       91.969033   654.889104   
std      0.483918     3.524049      4.301036       24.298981   351.914129   
min      0.000000     6.981000      9.710000       43.790000   143.500000   
25%      0.000000    11.700000     16.170000       75.170000   420.300000   
50%      0.000000    13.370000     18.840000       86.240000   551.100000   
75%      1.000000    15.780000     21.800000      104.100000   782.700000   
max      1.000000    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
count     569.000000  ...    569.000000     569.000000       569.000000   
mean        0.181162  ...     16.269190      25.677223       107.261213   
std         0.027414  ...      4.833242       6.146258        33.602542   
min         0.106000  ...      7.930000      12.020000        50.410000   
25%         0.161900  ...     13.010000      21.080000        84.110000   
50%         0.179200  ...     14.970000      25.410000        97.660000   
75%         0.195700  ...     18.790000      29.720000       125.400000   
max         0.304000  ...     36.040000      49.540000       251.200000   

        area_worst  smoothness_worst  compactness_worst  concavity_worst  \
count   569.000000        569.000000         569.000000       569.000000   
mean    880.583128          0.132369           0.254265         0.272188   
std     569.356993          0.022832           0.157336         0.208624   
min     185.200000          0.071170           0.027290         0.000000   
25%     515.300000          0.116600           0.147200         0.114500   
50%     686.500000          0.131300           0.211900         0.226700   
75%    1084.000000          0.146000           0.339100         0.382900   
max    4254.000000          0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  
count            569.000000      569.000000               569.000000  
mean               0.114606        0.290076                 0.083946  
std                0.065732        0.061867                 0.018061  
min                0.000000        0.156500                 0.055040  
25%                0.064930        0.250400                 0.071460  
50%                0.099930        0.282200                 0.080040  
75%                0.161400        0.317900                 0.092080  
max                0.291000        0.663800                 0.207500  

[8 rows x 31 columns]

In [ ]:
#X = df.iloc[:, 2 :4].values  #recupera somente 2 atributos
W = df.iloc[:, 2 : -1].values  #dataset completo
y = df['diagnosis'].values
print(W)
print(y)

[[ 17.99    10.38   122.8    ...   0.7119   0.2654   0.4601]
 [ 20.57    17.77   132.9    ...   0.2416   0.186    0.275 ]
 [ 19.69    21.25   130.     ...   0.4504   0.243    0.3613]
 ...
 [ 16.6     28.08   108.3    ...   0.3403   0.1418   0.2218]
 [ 20.6     29.33   140.1    ...   0.9387   0.265    0.4087]
 [  7.76    24.54    47.92   ...   0.       0.       0.2871]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0
 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1
 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 1 0 1 0 0 0 0 0 0 0

In [ ]:
kernels = ['linear', 'rbf', 'poly']
#kernels = ['rbf']
for kernel in kernels:
  svc1 = svm.SVC(kernel=kernel,gamma='scale').fit(W, y)
  print('saída dataset completo:',svc1.score(W, y))
 #svc = svm.SVC(kernel=kernel,gamma='scale').fit(X, y)
  #plotSVC('kernel=' + str(kernel))

saída dataset completo: 0.9630931458699473
saída dataset completo: 0.9226713532513181
saída dataset completo: 0.9138840070298769


In [ ]:
svc1.score(W, y) # acurácia

0.9138840070298769

In [ ]:
gammas = [0.1, 1, 6, 10, 100]
for gamma in gammas:
   svc1 = svm.SVC(kernel='rbf', gamma=gamma).fit(W, y)
   print(svc1.score(W, y))
   #svc = svm.SVC(kernel='rbf', gamma=gamma).fit(X, y)
   #plotSVC('gamma=' + str(gamma))

1.0
1.0
1.0
1.0
1.0


# GRID SEARCH
### Exemplo usando método que combina hiperparâmetros a fim de encontrar a melhor parametrização para o método.

In [ ]:
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV
parameters = {'kernel':('linear', 'rbf','poly'), 'C':[1, 10,100]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters,cv=5,scoring='accuracy')
clf.fit(W, y)



GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 10, 100],
                         'kernel': ('linear', 'rbf', 'poly')},
             scoring='accuracy')

In [ ]:
sorted(clf.cv_results_.keys())

['mean_fit_time',
 'mean_score_time',
 'mean_test_score',
 'param_C',
 'param_kernel',
 'params',
 'rank_test_score',
 'split0_test_score',
 'split1_test_score',
 'split2_test_score',
 'split3_test_score',
 'split4_test_score',
 'std_fit_time',
 'std_score_time',
 'std_test_score']

In [ ]:
print(clf.best_estimator_)

SVC(C=100, kernel='linear')


In [ ]:
print(clf.best_params_)

{'C': 100, 'kernel': 'linear'}


# A partir da identificação do melhor modelo, executar o fit (com todos os dados) e partir para a predição.

In [ ]:
# Construção do objeto SVM com a melhor configuração
melhor_modelo  = svm.SVC(kernel='linear', C=100)
melhor_modelo.fit(W, y)
melhor_modelo.score(W,y)

0.9666080843585237

In [ ]:
print('----Simulação da Predição----')
lista=[]
atributos = ["radius_mean","texture_mean","perimeter_mean","area_mean","smoothness_mean","compactness_mean","concavity_mean","concave_points_mean","symmetry_mean","fractal_dimension_mean","radius_se","texture_se","perimeter_se","area_se","smoothness_se","compactness_se","concavity_se","concave points_se","symmetry_se","fractal_dimension_se","radius_worst","texture_worst","perimeter_worst","area_worst","smoothness_worst","compactness_worst","concavity_worst","concave_points_worst","symmetry_worst"]
for i in range(len(atributos)):
  ret=float(input('Digite o :' + atributos[i]))
  lista.append(ret)

----Simulação da Predição----
Digite o :radius_mean17.99
Digite o :texture_mean10.38
Digite o :perimeter_mean122.80
Digite o :area_mean1001.0
Digite o :smoothness_mean0.11840
Digite o :compactness_mean0.27760
Digite o :concavity_mean0.3001
Digite o :concave_points_mean0.14710
Digite o :symmetry_mean0.2419
Digite o :fractal_dimension_mean0.07871
Digite o :radius_se1.0950
Digite o :texture_se0.9053
Digite o :perimeter_se8.589
Digite o :area_se153.40
Digite o :smoothness_se0.006399
Digite o :compactness_se0.04904
Digite o :concavity_se0.05373
Digite o :concave points_se0.01587
Digite o :symmetry_se0.03003
Digite o :fractal_dimension_se0.006193
Digite o :radius_worst25.38
Digite o :texture_worst17.33
Digite o :perimeter_worst184.60
Digite o :area_worst2019.0
Digite o :smoothness_worst0.1622
Digite o :compactness_worst0.6656
Digite o :concavity_worst0.7119
Digite o :concave_points_worst0.2654
Digite o :symmetry_worst0.4601
Digite o :fractal_dimension_worst0.11890


In [ ]:
lista2 = [17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601]
print('A classe desta predição é =>',melhor_modelo.predict([lista2]))


A classe desta predição é => [1]
