## Universidade de Caxias do Sul
## Pós-graduação em Ciência de Dados
### Prof Carine Webber
### Aprendizado de Máquina III - Redes Neurais

In [3]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import sklearn.metrics as metric
import numpy as np

In [1]:
X_treino=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_treino=[1, 
            1,
            1,
            0
           ]
X_teste=X_treino
y_teste=y_treino

# Perceptron

In [7]:
ptn = Perceptron(max_iter=50,tol=0.001)                    
ptn.fit(X_treino, y_treino)                    # treino
y_pred=ptn.predict(X_teste)                      # predição
print(y_pred)                                      # saída
accuracy=metric.accuracy_score(y_teste, y_pred, normalize=True)
print('acurácia=',accuracy)                         

[1 1 1 0]
acurácia= 1.0


In [8]:
print(ptn.intercept_, ptn.coef_) 

[-1.] [[2. 2.]]


# Rede Neural MLP


In [13]:
mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(1,1), activation='logistic') # parâmetros da rede neural
mlp.fit(X_treino, y_treino)                        # treino
y_pred=mlp.predict(X_teste)                        # predição
print(y_pred)                                      # apresenta a saída
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy)                      

[1 1 1 0]
acuracy= 1.0


In [19]:
print([coef.shape for coef in mlp.coefs_])  # arrays dos pesos sinápticos
mlp.coefs_                                  # pesos sinápticos 

[(2, 1), (1, 1), (1, 1)]


[array([[4.06097875],
        [4.09031442]]), array([[-7.93487225]]), array([[-15.20654461]])]

# Exercite !

- a) modifique os dados (X_treino, y_treino, X_teste)
- b) altere dos dados de binários para bipolares {-1, +1}
- c) altere a camada escondida do MLP: número de camadas (int) ou tamanho (n,m)
- d) altere o parâmetro solver do MLP: {'lbfgs', 'sgd', 'adam'}
- e) altere a função de ativação do MLP: {'identity', 'logistic', 'tanh', 'relu'}, default 'relu'

Orientação:
 - verifique a acurácia de cada predição


# Primeira tarefa: OU Bipolar
Troque as entradas {0, 1} por valores bipolares {-1, +1}. 
Utilize os dados e execute o Perceptron e o MLP, conforme o exemplo (4).

In [28]:
X_treino=[[1, 1], 
            [1, -1],
            [-1, 1],
            [-1, -1]
           ]
y_treino=[1, 
            1,
            1,
            -1
           ]
X_teste=X_treino
y_teste=y_treino

In [29]:
ptn = Perceptron(max_iter=50,tol=0.001)                    
ptn.fit(X_treino, y_treino)                    # treino
y_pred=ptn.predict(X_teste)                    # predição
print(y_pred)                                  # saída
accuracy=metric.accuracy_score(y_teste, y_pred, normalize=True)
print('acurácia=',accuracy)



[ 1  1  1 -1]
acurácia= 1.0


# Segunda tarefa: E Binário
Utilize os dados e execute o Perceptron e o MLP, conforme o exemplo (4).

In [ ]:
X_treino=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_treino=[1, 
            0,
            0,
            0
           ]
X_teste=X_treino
y_teste=y_treino

# Terceira tarefa: E Bipolar
Modifique os dados binários da segunda tarefa para dados bipolares. 
Utilize os dados e execute o Perceptron e o MLP.



# Quarta tarefa: dois neurônios de saída
Utilize o MLP para treinar e predizer o seguinte dataset. O que você observou ? Interprete a resposta.

In [ ]:
X_treino=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_treino=[[1, 1], 
            [1, 1],
            [1, 1],
            [0, 1]
           ]
X_teste=X_treino
y_teste=y_treino

# Quinta tarefa: XOR
Use o MLP para resolver o problema XOR Booleano. Como melhorar a acurácia? Qual configuração mínima de camadas escondidas é necessária para tornar a acurácia 1.0 (100% de acerto)?

In [ ]:
X_treino=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_treino=[1, 
            0,
            0,
            1
           ]
X_teste=X_treino
y_teste=y_treino

# Sexta tarefa: Tautologia
Treine o MLP para resolver o problema da Tautologia binária. Observe o comportamento.

In [ ]:
X_treino=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_treino=[1, 
            1,
            1,
            1
           ]
X_teste=X_treino
y_teste=y_treino

# Sétima tarefa: XNOR
Use o MLP para resolver o problema XNOR Booleano. Como melhorar a acurácia? Qual configuração mínima de camadas escondidas é necessária para tornar a acurácia 1.0 (100% de acerto)?

In [ ]:
X_treino=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_treino=[0, 
            1,
            1,
            0
           ]
X_teste=X_treino
y_teste=y_treino

# Oitava tarefa: Rede Neural com 3 entradas e 2 saídas
Experimente treinar os seguintes dados usando o MLP.  Altere o solver, as camadas escondidas e a função de ativação para melhorar a acurácia. 

In [ ]:
X_treino=[[ 1,  1,  0], 
            [ 1, -1, -1],
            [-1,  1,  1],
            [-1, -1,  1],
            [ 0,  1, -1],
            [ 0, -1, -1],
            [ 1,  1,  1]
           ]
y_treino=[[1, 0], 
            [0, 1],
            [1, 1],
            [1, 0],
            [1, 0],
            [1, 1],
            [1, 1]
           ]
X_teste=X_treino
y_teste=y_treino