In [122]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import sklearn.metrics as metric
import numpy as np
from sklearn.exceptions import ConvergenceWarning
from sklearn.model_selection import GridSearchCV
from sklearn.utils._testing import ignore_warnings


In [123]:
X_treino=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_treino=[1, 
            1,
            1,
            0
           ]
X_teste=X_treino
y_teste=y_treino

# Perceptron

In [124]:
ptn = Perceptron(max_iter=500,tol=0.001)                    
ptn.fit(X_treino, y_treino)                    # treino
y_pred=ptn.predict(X_teste)                      # predição
print(y_pred)                                      # saída
accuracy=metric.accuracy_score(y_teste, y_pred, normalize=True)
print('acurácia=',accuracy)                         

[1 1 1 0]
acurácia= 1.0


In [125]:
print(ptn.intercept_, ptn.coef_) 

[-1.] [[2. 2.]]


# Rede Neural MLP


In [126]:
mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(1,1), activation='logistic') # parâmetros da rede neural
mlp.fit(X_treino, y_treino)                        # treino
y_pred=mlp.predict(X_teste)                        # predição
print(y_pred)                                      # apresenta a saída
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy)                      

[1 1 1 0]
acuracy= 1.0


In [127]:
print([coef.shape for coef in mlp.coefs_])  # arrays dos pesos sinápticos
mlp.coefs_                                  # pesos sinápticos 

[(2, 1), (1, 1), (1, 1)]


[array([[-4.30700425],
        [-4.02422649]]), array([[-7.59680498]]), array([[15.27177413]])]

# Exercite !

- a) modifique os dados (X_treino, y_treino, X_teste)
- b) altere dos dados de binários para bipolares {-1, +1}
- c) altere a camada escondida do MLP: número de camadas (int) ou tamanho (n,m)
- d) altere o parâmetro solver do MLP: {'lbfgs', 'sgd', 'adam'}
- e) altere a função de ativação do MLP: {'identity', 'logistic', 'tanh', 'relu'}, default 'relu'

Orientação:
 - verifique a acurácia de cada predição


In [137]:
@ignore_warnings(category=ConvergenceWarning)
def search(X,y, cv1=2):
  param_grid = [
        {
            'activation' : ['identity', 'logistic', 'tanh', 'relu'],
            'solver' : ['lbfgs', 'sgd', 'adam'],
            'hidden_layer_sizes': [
             (1,),(2,),(3,),(4,),(5,),(6,),(7,),(8,),(9,),(10,),(11,), (12,),(13,),(14,),(15,),(16,),(17,),(18,),(19,),(20,),(21,)
             ]
        }
       ]
  clf = GridSearchCV(MLPClassifier(), param_grid, cv=cv1,
                            scoring='accuracy')
  clf.fit(X,y)


  print("Best parameters set found on development set:")
  print(clf.best_params_)

# Primeira tarefa: OU Bipolar
Troque as entradas {0, 1} por valores bipolares {-1, +1}. 
Utilize os dados e execute o Perceptron e o MLP, conforme o exemplo (4).

In [138]:
X_treino=[[1, 1], 
            [1, -1],
            [-1, 1],
            [-1, -1]
           ]
y_treino=[1, 
            1,
            1,
            -1
           ]
X_teste=X_treino
y_teste=y_treino

In [139]:
ptn = Perceptron(max_iter=50,tol=0.001)                    
ptn.fit(X_treino, y_treino)                    # treino
y_pred=ptn.predict(X_teste)                      # predição
print(y_pred)                                      # saída
accuracy=metric.accuracy_score(y_teste, y_pred, normalize=True)
print('acurácia=',accuracy)                         

[ 1  1  1 -1]
acurácia= 1.0


Executar o gridsearch para encontrar os melhores parametros (Não necessário nesta atividade)

In [140]:
search(X_treino,y_treino)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  UserWarning,


Best parameters set found on development set:
{'activation': 'identity', 'hidden_layer_sizes': (2,), 'solver': 'sgd'}


In [142]:
mlp = MLPClassifier(solver='sgd', hidden_layer_sizes=(2,), activation='identity') # parâmetros da rede neural
mlp.fit(X_treino, y_treino)                        # treino
y_pred=mlp.predict(X_teste)                        # predição
print(y_pred)                                      # apresenta a saída
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy)  


[ 1  1  1 -1]
acuracy= 1.0


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


Verificar todos os demais métodos solver e activation

In [ ]:
#{'identity', 'logistic', 'tanh', 'relu'}, default 'relu'
#MLP: {'lbfgs', 'sgd', 'adam'}
activation1 = ['identity', 'logistic', 'tanh', 'relu']
solver1 = ['lbfgs', 'sgd', 'adam']
for i in range(len(activation1)):
  for j in range(len(solver1)):
    print(solver1[j] + " + " + activation1[i])
    mlp = MLPClassifier(solver=solver1[j], hidden_layer_sizes=(2,1), activation=activation1[i]) # parâmetros da rede neural
    mlp.fit(X_treino, y_treino)                        # treino
    y_pred=mlp.predict(X_teste)                        # predição
    print(y_pred)                                      # apresenta a saída
    accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
    print('acuracy=',accuracy)

lbfgs + identity
[ 1  1  1 -1]
acuracy= 1.0
sgd + identity
[1 1 1 1]
acuracy= 0.75
adam + identity


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[1 1 1 1]
acuracy= 0.75
lbfgs + logistic
[ 1  1  1 -1]
acuracy= 1.0
sgd + logistic
[1 1 1 1]
acuracy= 0.75
adam + logistic


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[1 1 1 1]
acuracy= 0.75
lbfgs + tanh
[ 1  1  1 -1]
acuracy= 1.0
sgd + tanh


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[ 1  1  1 -1]
acuracy= 1.0
adam + tanh
[-1 -1 -1 -1]
acuracy= 0.25
lbfgs + relu
[ 1  1  1 -1]
acuracy= 1.0
sgd + relu
[1 1 1 1]
acuracy= 0.75
adam + relu
[1 1 1 1]
acuracy= 0.75


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


# Segunda tarefa: E Binário
Utilize os dados e execute o Perceptron e o MLP, conforme o exemplo (4).

In [143]:
X_treino=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_treino=[1, 
            0,
            0,
            0
           ]
X_teste=X_treino
y_teste=y_treino

In [144]:
ptn = Perceptron(max_iter=50,tol=0.001)                    
ptn.fit(X_treino, y_treino)                    # treino
y_pred=ptn.predict(X_teste)                      # predição
print(y_pred)                                      # saída
accuracy=metric.accuracy_score(y_teste, y_pred, normalize=True)
print('acurácia=',accuracy)                         

[1 0 0 0]
acurácia= 1.0


In [145]:
#{'identity', 'logistic', 'tanh', 'relu'}, default 'relu'
#MLP: {'lbfgs', 'sgd', 'adam'}
activation1 = ['identity', 'logistic', 'tanh', 'relu']
solver1 = ['lbfgs', 'sgd', 'adam']
for i in range(len(activation1)):
  for j in range(len(solver1)):
    print(solver1[j] + " + " + activation1[i])
    mlp = MLPClassifier(solver=solver1[j], hidden_layer_sizes=(4,4), activation=activation1[i]) # parâmetros da rede neural
    mlp.fit(X_treino, y_treino)                        # treino
    y_pred=mlp.predict(X_teste)                        # predição
    print(y_pred)                                      # apresenta a saída
    accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
    print('acuracy=',accuracy)   

lbfgs + identity
[1 0 0 0]
acuracy= 1.0
sgd + identity
[0 0 0 0]
acuracy= 0.75
adam + identity
[0 0 0 0]
acuracy= 0.75
lbfgs + logistic
[1 0 0 0]
acuracy= 1.0
sgd + logistic


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[0 0 0 0]
acuracy= 0.75
adam + logistic
[0 0 0 0]
acuracy= 0.75
lbfgs + tanh
[1 0 0 0]
acuracy= 1.0
sgd + tanh


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[0 0 0 0]
acuracy= 0.75
adam + tanh
[0 0 0 0]
acuracy= 0.75
lbfgs + relu
[1 0 0 0]
acuracy= 1.0
sgd + relu
[0 0 0 0]
acuracy= 0.75
adam + relu
[0 0 0 0]
acuracy= 0.75


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [147]:
mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(2,), activation='tanh') # parâmetros da rede neural
mlp.fit(X_treino, y_treino)                        # treino
y_pred=mlp.predict(X_teste)                        # predição
print(y_pred)                                      # apresenta a saída
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy)  


[1 0 0 0]
acuracy= 1.0


# Terceira tarefa: E Bipolar
Modifique os dados binários da segunda tarefa para dados bipolares. 
Utilize os dados e execute o Perceptron e o MLP.



In [148]:
X_treino=[[1, 1], 
            [1, -1],
            [-1, 1],
            [-1, -1]
           ]
y_treino=[1, 
            1,
            1,
            -1
           ]
X_teste=X_treino
y_teste=y_treino

In [149]:
ptn = Perceptron(max_iter=50,tol=0.001)                    
ptn.fit(X_treino, y_treino)                    # treino
y_pred=ptn.predict(X_teste)                      # predição
print(y_pred)                                      # saída
accuracy=metric.accuracy_score(y_teste, y_pred, normalize=True)
print('acurácia=',accuracy)  

[ 1  1  1 -1]
acurácia= 1.0


In [150]:
#{'identity', 'logistic', 'tanh', 'relu'}, default 'relu'
#MLP: {'lbfgs', 'sgd', 'adam'}
activation1 = ['identity', 'logistic', 'tanh', 'relu']
solver1 = ['lbfgs', 'sgd', 'adam']
for i in range(len(activation1)):
  for j in range(len(solver1)):
    print(solver1[j] + " + " + activation1[i])
    mlp = MLPClassifier(solver=solver1[j], hidden_layer_sizes=(4,4), activation=activation1[i]) # parâmetros da rede neural
    mlp.fit(X_treino, y_treino)                        # treino
    y_pred=mlp.predict(X_teste)                        # predição
    print(y_pred)                                      # apresenta a saída
    accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
    print('acuracy=',accuracy)   

lbfgs + identity
[ 1  1  1 -1]
acuracy= 1.0
sgd + identity
[ 1  1  1 -1]
acuracy= 1.0
adam + identity
[ 1  1  1 -1]
acuracy= 1.0
lbfgs + logistic
[ 1  1  1 -1]
acuracy= 1.0
sgd + logistic


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[1 1 1 1]
acuracy= 0.75
adam + logistic
[1 1 1 1]
acuracy= 0.75
lbfgs + tanh
[ 1  1  1 -1]
acuracy= 1.0
sgd + tanh


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[1 1 1 1]
acuracy= 0.75
adam + tanh
[ 1  1  1 -1]
acuracy= 1.0
lbfgs + relu
[ 1  1  1 -1]
acuracy= 1.0
sgd + relu


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[1 1 1 1]
acuracy= 0.75
adam + relu
[1 1 1 1]
acuracy= 0.75


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [151]:
mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(2,), activation='relu') # parâmetros da rede neural
mlp.fit(X_treino, y_treino)                        # treino
y_pred=mlp.predict(X_teste)                        # predição
print(y_pred)                                      # apresenta a saída
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy) 

[ 1  1  1 -1]
acuracy= 1.0


# Quarta tarefa: dois neurônios de saída
Utilize o MLP para treinar e predizer o seguinte dataset. O que você observou ? Interprete a resposta.

In [152]:
X_treino=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_treino=[[1, 1], 
            [1, 1],
            [1, 1],
            [0, 1]
           ]
X_teste=X_treino
y_teste=y_treino

In [153]:
#{'identity', 'logistic', 'tanh', 'relu'}, default 'relu'
#MLP: {'lbfgs', 'sgd', 'adam'}
activation1 = ['identity', 'logistic', 'tanh', 'relu']
solver1 = ['lbfgs', 'sgd', 'adam']
for i in range(len(activation1)):
  for j in range(len(solver1)):
    print(solver1[j] + " + " + activation1[i])
    mlp = MLPClassifier(solver=solver1[j], hidden_layer_sizes=(4,4), activation=activation1[i]) # parâmetros da rede neural
    mlp.fit(X_treino, y_treino)                        # treino
    y_pred=mlp.predict(X_teste)                        # predição
    print(y_pred)                                      # apresenta a saída
    accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
    print('acuracy=',accuracy)

lbfgs + identity
[[1 1]
 [1 1]
 [1 1]
 [0 1]]
acuracy= 1.0
sgd + identity
[[1 1]
 [1 1]
 [1 1]
 [0 1]]
acuracy= 1.0
adam + identity
[[1 1]
 [1 1]
 [1 1]
 [1 1]]
acuracy= 0.875
lbfgs + logistic


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[[1 1]
 [1 1]
 [1 1]
 [0 1]]
acuracy= 1.0
sgd + logistic
[[1 1]
 [1 1]
 [1 1]
 [1 1]]
acuracy= 0.875
adam + logistic


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[[1 1]
 [1 1]
 [1 1]
 [1 1]]
acuracy= 0.875
lbfgs + tanh
[[1 1]
 [1 1]
 [1 1]
 [0 1]]
acuracy= 1.0
sgd + tanh
[[1 1]
 [1 1]
 [1 1]
 [1 1]]
acuracy= 0.875
adam + tanh
[[1 1]
 [1 1]
 [1 1]
 [0 1]]
acuracy= 1.0
lbfgs + relu


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[[1 1]
 [1 1]
 [1 1]
 [0 1]]
acuracy= 1.0
sgd + relu
[[1 1]
 [1 1]
 [0 1]
 [0 1]]
acuracy= 0.875
adam + relu
[[1 1]
 [1 1]
 [0 1]
 [0 1]]
acuracy= 0.875


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [154]:
mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(4,), activation='identity') # parâmetros da rede neural
mlp.fit(X_treino, y_treino)                        # treino
y_pred=mlp.predict(X_teste)                        # predição
print(y_pred)                                      # apresenta a saída
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy) 

[[1 1]
 [1 1]
 [1 1]
 [0 1]]
acuracy= 1.0


# Quinta tarefa: XOR
Use o MLP para resolver o problema XOR Booleano. Como melhorar a acurácia? Qual configuração mínima de camadas escondidas é necessária para tornar a acurácia 1.0 (100% de acerto)?

In [155]:
X_treino=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_treino=[1, 
            0,
            0,
            1
           ]
X_teste=X_treino
y_teste=y_treino

In [ ]:
search(X_treino,y_treino)

Best parameters set found on development set:
{'activation': 'identity', 'hidden_layer_sizes': (4,), 'solver': 'adam'}


In [156]:
#{'identity', 'logistic', 'tanh', 'relu'}, default 'relu'
#MLP: {'lbfgs', 'sgd', 'adam'}
activation1 = ['identity', 'logistic', 'tanh', 'relu']
solver1 = ['lbfgs', 'sgd', 'adam']
for i in range(len(activation1)):
  for j in range(len(solver1)):
    print(solver1[j] + " + " + activation1[i])
    mlp = MLPClassifier(solver=solver1[j], hidden_layer_sizes=(2,2), activation=activation1[i]) # parâmetros da rede neural
    mlp.fit(X_treino, y_treino)                        # treino
    y_pred=mlp.predict(X_teste)                        # predição
    print(y_pred)                                      # apresenta a saída
    accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
    print('acuracy=',accuracy)

lbfgs + identity
[0 1 0 1]
acuracy= 0.5
sgd + identity
[0 0 0 0]
acuracy= 0.5
adam + identity
[1 1 1 1]
acuracy= 0.5
lbfgs + logistic


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[1 0 0 1]
acuracy= 1.0
sgd + logistic
[1 1 1 1]
acuracy= 0.5
adam + logistic
[0 0 1 0]
acuracy= 0.25
lbfgs + tanh
[1 0 0 1]
acuracy= 1.0
sgd + tanh
[1 1 1 1]
acuracy= 0.5
adam + tanh


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[0 0 1 0]
acuracy= 0.25
lbfgs + relu
[1 1 1 1]
acuracy= 0.5
sgd + relu
[1 1 1 1]
acuracy= 0.5
adam + relu
[1 1 1 1]
acuracy= 0.5


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


10x10 camadas

adam + relu
[1 0 0 1]
acuracy= 1.0

adam + tanh
[1 0 0 1]
acuracy= 1.0

lbfgs + relu
[1 0 0 1]
acuracy= 1.0

lbfgs + tanh
[1 0 0 1]
acuracy= 1.0





In [157]:
mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(10,), activation='relu') # parâmetros da rede neural
mlp.fit(X_treino, y_treino)                        # treino
y_pred=mlp.predict(X_teste)                        # predição
print(y_pred)                                      # apresenta a saída
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy) 

[1 0 0 1]
acuracy= 1.0


# Sexta tarefa: Tautologia
Treine o MLP para resolver o problema da Tautologia binária. Observe o comportamento.

In [158]:
X_treino=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_treino=[1, 
            1,
            1,
            1
           ]
X_teste=X_treino
y_teste=y_treino

In [ ]:
search(X_treino,y_treino)

Best parameters set found on development set:
{'activation': 'identity', 'hidden_layer_sizes': (1,), 'solver': 'lbfgs'}


{'activation': 'identity', 'hidden_layer_sizes': (1,), 'solver': 'lbfgs'}

In [159]:
#{'identity', 'logistic', 'tanh', 'relu'}, default 'relu'
#MLP: {'lbfgs', 'sgd', 'adam'}
activation1 = ['identity', 'logistic', 'tanh', 'relu']
solver1 = ['lbfgs', 'sgd', 'adam']
for i in range(len(activation1)):
  for j in range(len(solver1)):
    print(solver1[j] + " + " + activation1[i])
    mlp = MLPClassifier(solver=solver1[j], hidden_layer_sizes=(4,4), activation=activation1[i]) # parâmetros da rede neural
    mlp.fit(X_treino, y_treino)                        # treino
    y_pred=mlp.predict(X_teste)                        # predição
    print(y_pred)                                      # apresenta a saída
    accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
    print('acuracy=',accuracy)

lbfgs + identity
[1 1 1 1]
acuracy= 1.0
sgd + identity
[1 1 1 1]
acuracy= 1.0
adam + identity
[1 1 1 1]
acuracy= 1.0
lbfgs + logistic
[1 1 1 1]
acuracy= 1.0
sgd + logistic


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[1 1 1 1]
acuracy= 1.0
adam + logistic
[1 1 1 1]
acuracy= 1.0
lbfgs + tanh
[1 1 1 1]
acuracy= 1.0
sgd + tanh


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[1 1 1 1]
acuracy= 1.0
adam + tanh
[1 1 1 1]
acuracy= 1.0
lbfgs + relu
[1 1 1 1]
acuracy= 1.0
sgd + relu


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[1 1 1 1]
acuracy= 1.0
adam + relu
[1 1 1 1]
acuracy= 1.0


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [160]:
mlp = MLPClassifier(solver='adam', hidden_layer_sizes=(1,), activation='logistic') # parâmetros da rede neural
mlp.fit(X_treino, y_treino)                        # treino
y_pred=mlp.predict(X_teste)                        # predição
print(y_pred)                                      # apresenta a saída
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy)  

[1 1 1 1]
acuracy= 1.0


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


# Sétima tarefa: XNOR
Use o MLP para resolver o problema XNOR Booleano. Como melhorar a acurácia? Qual configuração mínima de camadas escondidas é necessária para tornar a acurácia 1.0 (100% de acerto)?

In [161]:
X_treino=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_treino=[0, 
            1,
            1,
            0
           ]
X_teste=X_treino
y_teste=y_treino

In [162]:
#{'identity', 'logistic', 'tanh', 'relu'}, default 'relu'
#MLP: {'lbfgs', 'sgd', 'adam'}
activation1 = ['identity', 'logistic', 'tanh', 'relu']
solver1 = ['lbfgs', 'sgd', 'adam']
for i in range(len(activation1)):
  for j in range(len(solver1)):
    print(solver1[j] + " + " + activation1[i])
    mlp = MLPClassifier(solver=solver1[j], hidden_layer_sizes=(4,4), activation=activation1[i]) # parâmetros da rede neural
    mlp.fit(X_treino, y_treino)                        # treino
    y_pred=mlp.predict(X_teste)                        # predição
    print(y_pred)                                      # apresenta a saída
    accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
    print('acuracy=',accuracy)

lbfgs + identity
[0 1 0 1]
acuracy= 0.5
sgd + identity
[0 1 0 0]
acuracy= 0.75
adam + identity
[1 0 1 1]
acuracy= 0.25
lbfgs + logistic
[1 0 1 0]
acuracy= 0.5
sgd + logistic


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[0 0 0 0]
acuracy= 0.5
adam + logistic
[0 1 0 1]
acuracy= 0.5
lbfgs + tanh
[0 1 1 0]
acuracy= 1.0
sgd + tanh
[1 1 1 1]
acuracy= 0.5
adam + tanh


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[0 1 0 1]
acuracy= 0.5
lbfgs + relu
[0 1 1 1]
acuracy= 0.75
sgd + relu
[1 1 1 1]
acuracy= 0.5
adam + relu
[0 1 0 0]
acuracy= 0.75


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [163]:
mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(4,), activation='tanh') # parâmetros da rede neural
mlp.fit(X_treino, y_treino)                        # treino
y_pred=mlp.predict(X_teste)                        # predição
print(y_pred)                                      # apresenta a saída
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy)  

[0 1 1 0]
acuracy= 1.0


# Oitava tarefa: Rede Neural com 3 entradas e 2 saídas
Experimente treinar os seguintes dados usando o MLP.  Altere o solver, as camadas escondidas e a função de ativação para melhorar a acurácia. 

In [164]:
X_treino=[[ 1,  1,  0], 
            [ 1, -1, -1],
            [-1,  1,  1],
            [-1, -1,  1],
            [ 0,  1, -1],
            [ 0, -1, -1],
            [ 1,  1,  1]
           ]
y_treino=[[1, 0], 
            [0, 1],
            [1, 1],
            [1, 0],
            [1, 0],
            [1, 1],
            [1, 1]
           ]
X_teste=X_treino
y_teste=y_treino


In [165]:
#{'identity', 'logistic', 'tanh', 'relu'}, default 'relu'
#MLP: {'lbfgs', 'sgd', 'adam'}
activation1 = ['identity', 'logistic', 'tanh', 'relu']
solver1 = ['lbfgs', 'sgd', 'adam']
for i in range(len(activation1)):
  for j in range(len(solver1)):
    print(solver1[j] + " + " + activation1[i])
    mlp = MLPClassifier(solver=solver1[j], hidden_layer_sizes=(4,4), activation=activation1[i]) # parâmetros da rede neural
    mlp.fit(X_treino, y_treino)                        # treino
    y_pred=mlp.predict(X_teste)                        # predição
    print(y_pred)                                      # apresenta a saída
    accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
    print('acuracy=',accuracy)

lbfgs + identity
[[1 1]
 [0 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]]
acuracy= 0.7857142857142857
sgd + identity
[[1 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]]
acuracy= 0.8571428571428571
adam + identity
[[1 1]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]]
acuracy= 0.6428571428571429
lbfgs + logistic


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[[1 0]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]]
acuracy= 1.0
sgd + logistic
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
acuracy= 0.7142857142857143
adam + logistic
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
acuracy= 0.7142857142857143
lbfgs + tanh


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[[1 0]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]]
acuracy= 1.0
sgd + tanh
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
acuracy= 0.7142857142857143
adam + tanh


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]]
acuracy= 0.7857142857142857
lbfgs + relu
[[1 0]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]]
acuracy= 1.0
sgd + relu
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
acuracy= 0.7142857142857143
adam + relu
[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]
acuracy= 0.6428571428571429


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [166]:
mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(4,), activation='logistic') # parâmetros da rede neural
mlp.fit(X_treino, y_treino)                        # treino
y_pred=mlp.predict(X_teste)                        # predição
print(y_pred)                                      # apresenta a saída
accuracy=metric.accuracy_score(np.array(y_teste).flatten(), np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy)  

ValueError: ignored